import re, sys
from pathlib import Path

PO_DIR = Path(__file__).with_name("locales")
PATTERN = re.compile(r'_\(\s*[\'\"]([^\'\"]+)[\'\"]\s*\)')
LANGS = ["en", "zh"]


def find_strings(root: Path):
    """Return mapping of msgid -> set of "path:line" occurrences."""

    keys = {}
    for p in root.rglob("*.py"):
        if p.name.startswith(("i18n_extract", "i18n.py")):
            continue
        rel = p.relative_to(root).as_posix()
        for lineno, line in enumerate(
            p.read_text(encoding="utf-8", errors="ignore").splitlines(), 1
        ):
            for match in PATTERN.finditer(line):
                key = match.group(1)
                keys.setdefault(key, set()).add(f"{rel}:{lineno}")
    return keys

def load_po(lang: str) -> dict:
    path = PO_DIR / f"messages_{lang}.po"
    if not path.exists():
        return {}
    entries = {}
    current_id = None
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if line.startswith("msgid "):
            current_id = line[7:-1]  # strip msgid "..."
        elif line.startswith("msgstr ") and current_id is not None:
            entries[current_id] = line[8:-1]
            current_id = None
    return entries

def dump_po(lang: str, entries: dict, locations: dict):
    path = PO_DIR / f"messages_{lang}.po"
    PO_DIR.mkdir(exist_ok=True)
    lines = [
        "# Auto-generated by i18n_extract.py",
        "msgid \"\"",
        "msgstr \"\"",
        "\"Content-Type: text/plain; charset=UTF-8\\n\"",
        "",
    ]
    for msgid in sorted(entries.keys()):
        msgstr = entries[msgid] or ""
        for loc in sorted(locations.get(msgid, [])):
            lines.append(f"#: {loc}")
        lines.append(f'msgid "{msgid}"')
        lines.append(f'msgstr "{msgstr}"')
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")

def main():
    project_root = Path(__file__).parent.parent
    locations = find_strings(project_root)
    for lang in LANGS:
        existing = load_po(lang)
        for k in locations.keys():
            if k.startswith("Example:"):
                pass
        merged = {k: existing.get(k, "") for k in locations}
        dump_po(lang, merged, locations)
    print(f"Found {len(LANGS)} strings. Updated: {PO_DIR}/messages_<lang>.po")

if __name__ == "__main__":
    sys.exit(main())